version: '3.5'

services:
        # selenium-chrome-server:
        #  image: selenium/standalone-chrome
        #  volumes:
        #   - /dev/shm:/dev/shm
        # nginx:
        #  image: nginx:latest
        #  volumes:
        #   - ./nginx-balancer.conf:/etc/nginx/nginx.conf:ro
        #  depends_on:
        #      - selenium-chrome-server
        #  ports:
        #   - "4444:4444"
  neo4j:
    image: neo4j
    networks:
      - order-master
    volumes:
      - /var/lib/neo4j/conf:/conf
      - /var/lib/neo4j/data:/data
      - /var/lib/neo4j/logs:/logs
    environment:
      - NEO4J_dbms_default__advertised__address=neo4j

  network-builder:
    depends_on:
      - neo4j
    image: ralfeus/network-builder
    networks:
      - order-master
    ports:
      - 5001:5001
    volumes:
      - /var/www/order/network_builder/config.json:/app/config.json

  rabbitmq:
    image: rabbitmq:3-management
    #  depends_on:
    #   - selenium-chrome-server
    networks:
      - order-master
    ports:
    - "5672:5672"
    - "15672:15672"

     # celery:
     #  image: ralfeus/order-master
     #  depends_on:
     #    - selenium-chrome-server
     #    - rabbitmq
     #  command: celery -A app worker -E --loglevel=INFO --concurrency 1 -B --schedule-filename /tmp/celerybeat-schedule
