version: '3.5'

services:
  celery:
    image: ralfeus/order-master
    depends_on:
      - selenium-chrome-server
      - rabbitmq
    command: celery -A app worker -E --loglevel=INFO --concurrency 1 -B

