version: '3.5'

services:
  neo4j:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - /var/lib/neo4j/conf:/conf
      - /var/lib/neo4j/data:/data
      - /var/lib/neo4j/logs:/logs
      - /var/lib/neo4j/plugins:/plugins
    environment:
      - NEO4J_dbms_default__advertised__address=neo4j

  network-manager:
    depends_on:
      - neo4j
    image: ralfeus/network-manager:stable
    ports:
      - 5001:5001
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /var/www/order/network_builder/config.json:/app/config.json
    environment: 
      - NEO4J_URL=bolt://neo4j:1@neo4j:7687
      - SOCKS5_PROXY=host.docker.internal:9050
    privileged: true

  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - "5672:5672"
    - "15672:15672"

  metabase:
    image: metabase/metabase:latest
    ports:
      - 3001:3000
    volumes:
      - /var/lib/metabase/plugins:/plugins
    environment:
      - MB_SITE_URL=https://request.talya.kim/mb/
      - MB_DB_TYPE=mysql
      - MB_DB_CONNECTION_URI=jdbc:mysql://172.17.0.1:3306/metabase?user=metabase&password=metabase
      - JAVA_TIMEZONE=Asia/Seoul

     # celery:
     #  image: ralfeus/order-master
     #  depends_on:
     #    - rabbitmq
     #  command: celery -A app worker -E --loglevel=INFO --concurrency 1 -B --schedule-filename /tmp/celerybeat-schedule
