"""update

Revision ID: 0002
Revises: 0001
Create Date: 2026-04-08 09:52:11.656505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_flat_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipping_rate_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_type_code', sa.String(length=16), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('max_weight_kg', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('shipments', sa.Column('weight_kg', sa.Numeric(precision=10, scale=3), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'weight_kg')
    op.drop_table('shipping_rate_entries')
    op.drop_table('shipping_flat_rates')
    # ### end Alembic commands ###
