"""Network nodes

Revision ID: 02a0b7bd0fe5
Revises: a236ef13b695
Create Date: 2021-02-21 06:44:39.026716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '02a0b7bd0fe5'
down_revision = 'a236ef13b695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('network_nodes', 'center',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=32),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.drop_index('ix_network_nodes_has_children', table_name='network_nodes')
    op.drop_column('network_nodes', 'has_children')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('network_nodes', sa.Column('has_children', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.create_index('ix_network_nodes_has_children', 'network_nodes', ['has_children'], unique=False)
    op.alter_column('network_nodes', 'center',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(collation='utf8_unicode_ci', length=32),
               existing_nullable=True)
    # ### end Alembic commands ###
