"""refactoring

Revision ID: 078fe3bb3fe2
Revises: 5912b4c35c7a
Create Date: 2020-07-28 09:34:35.844680

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '078fe3bb3fe2'
down_revision = '5912b4c35c7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('when_created', sa.DateTime(), nullable=True))
    op.drop_column('orders', 'time_created')
    op.add_column('products', sa.Column('when_changed', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('when_created', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('when_changed', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('when_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'when_created')
    op.drop_column('users', 'when_changed')
    op.drop_column('products', 'when_created')
    op.drop_column('products', 'when_changed')
    op.add_column('orders', sa.Column('time_created', mysql.DATETIME(), nullable=True))
    op.drop_column('orders', 'when_created')
    # ### end Alembic commands ###
