"""country priority

Revision ID: 09d4caed252e
Revises: 18d483deca4b
Create Date: 2020-10-21 18:25:45.028442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '09d4caed252e'
down_revision = '18d483deca4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('sort_order', sa.Integer(), nullable=True))
    op.execute("UPDATE countries SET sort_order=999")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('countries', 'sort_order')
    # ### end Alembic commands ###
