"""payment method instructions

Revision ID: 0bdc8953cd67
Revises: cb02ec280203
Create Date: 2021-01-28 19:58:31.046180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bdc8953cd67'
down_revision = 'cb02ec280203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_methods', sa.Column('instructions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_methods', 'instructions')
    # ### end Alembic commands ###
