"""Network nodes

Revision ID: 0ecfd4656e45
Revises: 47170d8c53fb
Create Date: 2021-02-21 07:11:53.404319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ecfd4656e45'
down_revision = '47170d8c53fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_nodes',
    sa.Column('when_created', sa.DateTime(), nullable=True),
    sa.Column('when_changed', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('rank', sa.String(length=16), nullable=True),
    sa.Column('highest_rank', sa.String(length=16), nullable=True),
    sa.Column('center', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=32), nullable=True),
    sa.Column('signup_date', sa.Date(), nullable=True),
    sa.Column('pv', sa.Integer(), nullable=True),
    sa.Column('network_pv', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.String(length=10), nullable=True),
    sa.Column('left_id', sa.String(length=10), nullable=True),
    sa.Column('right_id', sa.String(length=10), nullable=True),
    sa.Column('built_tree', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['left_id'], ['network_nodes.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['network_nodes.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['network_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_nodes_built_tree'), 'network_nodes', ['built_tree'], unique=False)
    op.create_index(op.f('ix_network_nodes_rank'), 'network_nodes', ['rank'], unique=False)
    op.create_index(op.f('ix_network_nodes_when_created'), 'network_nodes', ['when_created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_network_nodes_when_created'), table_name='network_nodes')
    op.drop_index(op.f('ix_network_nodes_rank'), table_name='network_nodes')
    op.drop_index(op.f('ix_network_nodes_built_tree'), table_name='network_nodes')
    op.drop_table('network_nodes')
    # ### end Alembic commands ###
