"""enable/disable company

Revision ID: 0f4ca0502c59
Revises: be17c0af1d19
Create Date: 2022-11-24 09:00:09.399297

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f4ca0502c59'
down_revision = 'be17c0af1d19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('enabled', sa.Boolean(), nullable=True))
    op.execute("UPDATE companies SET enabled=1")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'enabled')
    # ### end Alembic commands ###
