"""transaction customer balance

Revision ID: 108624ed5665
Revises: 695110072936
Create Date: 2020-12-17 15:45:37.577354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '108624ed5665'
down_revision = '695110072936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('customer_balance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'customer_balance')
    # ### end Alembic commands ###
