"""purchase order add company

Revision ID: 167b16148b7c
Revises: a1ff50d1dc23
Create Date: 2020-10-12 14:45:26.032119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '167b16148b7c'
down_revision = 'a1ff50d1dc23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_orders', 'payment_account',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=16),
               type_=sa.String(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_orders', 'payment_account',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(collation='utf8_unicode_ci', length=16),
               existing_nullable=True)
    # ### end Alembic commands ###
