"""product - name

Revision ID: 1a30f2e460bc
Revises: 78690a8ed199
Create Date: 2020-07-21 09:54:08.671647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a30f2e460bc'
down_revision = '78690a8ed199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('name', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_column('products', 'name')
    # ### end Alembic commands ###
