"""box weight

Revision ID: 26142232272e
Revises: f1160cb14b97
Create Date: 2020-08-04 17:09:46.367342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26142232272e'
down_revision = 'f1160cb14b97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_krw', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('shipping_rur', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('shipping_usd', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('subtotal_krw', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('subtotal_rur', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('subtotal_usd', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('total_krw', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('total_rur', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('total_usd', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('total_weight', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'total_weight')
    op.drop_column('orders', 'total_usd')
    op.drop_column('orders', 'total_rur')
    op.drop_column('orders', 'total_krw')
    op.drop_column('orders', 'subtotal_usd')
    op.drop_column('orders', 'subtotal_rur')
    op.drop_column('orders', 'subtotal_krw')
    op.drop_column('orders', 'shipping_usd')
    op.drop_column('orders', 'shipping_rur')
    op.drop_column('orders', 'shipping_krw')
    # ### end Alembic commands ###
