"""invoice

Revision ID: 274ae7b2b4dc
Revises: c3476be93596
Create Date: 2020-07-31 08:41:56.871408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '274ae7b2b4dc'
down_revision = 'c3476be93596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('seq_num', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_invoices_when_created'), 'invoices', ['when_created'], unique=False)
    op.add_column('order_products', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_products', 'price')
    op.drop_index(op.f('ix_invoices_when_created'), table_name='invoices')
    op.drop_column('invoices', 'seq_num')
    # ### end Alembic commands ###
