"""export_id

Revision ID: 2de6c032ab2c
Revises: 365109f929b6
Create Date: 2021-08-10 10:49:22.020827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2de6c032ab2c'
down_revision = '365109f929b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('export_id', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'export_id')
    # ### end Alembic commands ###
