"""PO add vendor ID

Revision ID: 2e5885e58757
Revises: 20ab3b1f8420
Create Date: 2020-10-26 21:47:42.248274

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e5885e58757'
down_revision = '20ab3b1f8420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'tax_id_1',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=3),
               existing_nullable=True)
    op.alter_column('companies', 'tax_id_2',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=2),
               existing_nullable=True)
    op.alter_column('companies', 'tax_id_3',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=5),
               existing_nullable=True)
    op.add_column('purchase_orders', sa.Column('vendor_po_id', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'vendor_po_id')
    op.alter_column('companies', 'tax_id_3',
               existing_type=sa.String(length=5),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('companies', 'tax_id_2',
               existing_type=sa.String(length=2),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('companies', 'tax_id_1',
               existing_type=sa.String(length=3),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
