"""product image

Revision ID: 2f8807df4af0
Revises: 5053d16e8bb6
Create Date: 2021-06-29 12:49:09.606330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f8807df4af0'
down_revision = '5053d16e8bb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'files', ['image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'image_id')
    # ### end Alembic commands ###
