"""payment methods

Revision ID: 32141851936f
Revises: 38bd2ff9a112
Create Date: 2020-09-28 18:37:09.818864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32141851936f'
down_revision = '38bd2ff9a112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('when_created', sa.DateTime(), nullable=True),
    sa.Column('when_changed', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_methods_when_created'), 'payment_methods', ['when_created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_methods_when_created'), table_name='payment_methods')
    op.drop_table('payment_methods')
    # ### end Alembic commands ###
