"""extended tax info

Revision ID: 3791f8b3e6e2
Revises: 2f8807df4af0
Create Date: 2021-07-10 17:23:37.645000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3791f8b3e6e2'
down_revision = '2f8807df4af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('business_sectors', sa.String(length=64), nullable=True))
    op.add_column('companies', sa.Column('business_status', sa.String(length=64), nullable=True))
    op.add_column('companies', sa.Column('tax_address_id', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('tax_phone', sa.String(length=13), nullable=True))
    op.add_column('companies', sa.Column('tax_simplified', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'companies', 'addresses', ['tax_address_id'], ['id'])
    op.execute('UPDATE companies SET tax_simplified=1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'tax_simplified')
    op.drop_column('companies', 'tax_phone')
    op.drop_column('companies', 'tax_address_id')
    op.drop_column('companies', 'business_status')
    op.drop_column('companies', 'business_sectors')
    # ### end Alembic commands ###
