"""transactions amount received

Revision ID: 38171686e9ea
Revises: 274ae7b2b4dc
Create Date: 2020-08-03 17:11:12.475728

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38171686e9ea'
down_revision = '274ae7b2b4dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('amount_received_krw', sa.Integer(), nullable=True))
    op.alter_column('transactions', column_name='amount_krw', 
        new_column_name='amount_sent_krw', 
        existing_type=mysql.INTEGER(), existing_nullable=True)
    op.alter_column('transactions', column_name='amount_original',
        new_column_name='amount_sent_original', 
        existing_type=mysql.DECIMAL(precision=10, scale=2), existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', column_name='amount_sent_krw', 
        new_column_name='amount_krw', 
        existing_type=mysql.INTEGER(), existing_nullable=True)
    op.alter_column('transactions', column_name='amount_sent_original',
        new_column_name='amount_original', 
        existing_type=mysql.DECIMAL(precision=10, scale=2), existing_nullable=True)
    op.drop_column('transactions', 'amount_received_krw')
    # ### end Alembic commands ###
