"""payment sender name

Revision ID: 4127588062a6
Revises: 2de6c032ab2c
Create Date: 2021-09-02 15:16:13.915567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4127588062a6'
down_revision = '2de6c032ab2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('sender_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'sender_name')
    # ### end Alembic commands ###
