"""shpping in order

Revision ID: 41bb56d948dc
Revises: 8ce433ae0d89
Create Date: 2020-08-17 18:33:31.176769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41bb56d948dc'
down_revision = '8ce433ae0d89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_method_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'shipping', ['shipping_method_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'shipping_method_id')
    # ### end Alembic commands ###
