"""advanced taxation

Revision ID: 4bad9cf69f5f
Revises: 675c8fc36c31
Create Date: 2021-07-11 07:54:55.540007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4bad9cf69f5f'
down_revision = '675c8fc36c31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('business_category', sa.String(length=64), nullable=True))
    op.add_column('companies', sa.Column('business_type', sa.String(length=64), nullable=True))
    op.add_column('companies', sa.Column('email', sa.String(length=64), nullable=True))
    op.drop_column('companies', 'business_sectors')
    op.drop_column('companies', 'business_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('business_status', mysql.VARCHAR(collation='utf8_unicode_ci', length=64), nullable=True))
    op.add_column('companies', sa.Column('business_sectors', mysql.VARCHAR(collation='utf8_unicode_ci', length=64), nullable=True))
    op.drop_column('companies', 'email')
    op.drop_column('companies', 'business_type')
    op.drop_column('companies', 'business_category')
    # ### end Alembic commands ###
