"""payment rework

Revision ID: 4c761fd374bc
Revises: d34ae5586298
Create Date: 2020-12-11 22:05:18.049027

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c761fd374bc'
down_revision = 'd34ae5586298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('when_created', sa.DateTime(), nullable=True),
    sa.Column('when_changed', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('amount_sent_original', sa.Numeric(scale=2), nullable=True),
    sa.Column('amount_sent_krw', sa.Integer(), nullable=True),
    sa.Column('amount_received_krw', sa.Integer(), nullable=True),
    sa.Column('payment_method_id', sa.Integer(), nullable=True),
    sa.Column('evidence_image', sa.String(length=256), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='paymentstatus'), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_when_created'), 'payments', ['when_created'], unique=False)
    op.create_table('payments_orders',
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], )
    )
    op.drop_table('transactions_orders')
    op.add_column('orders', sa.Column('payment_method_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'payment_methods', ['payment_method_id'], ['id'])
    op.add_column('transactions', sa.Column('amount', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.drop_constraint('transactions_ibfk_1', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_ibfk_4', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_ibfk_2', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'users', ['customer_id'], ['id'])
    op.drop_column('transactions', 'amount_received_krw')
    op.drop_column('transactions', 'amount_sent_krw')
    op.drop_column('transactions', 'currency_code')
    op.drop_column('transactions', 'amount_sent_original')
    op.drop_column('transactions', 'status')
    op.drop_column('transactions', 'proof_image')
    op.drop_column('transactions', 'payment_method_id')
    op.drop_column('transactions', 'changed_by_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('changed_by_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('payment_method_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('proof_image', mysql.VARCHAR(collation='utf8_unicode_ci', length=256), nullable=True))
    op.add_column('transactions', sa.Column('status', mysql.ENUM('pending', 'approved', 'rejected', 'cancelled', collation='utf8_unicode_ci'), nullable=True))
    op.add_column('transactions', sa.Column('amount_sent_original', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('transactions', sa.Column('currency_code', mysql.VARCHAR(collation='utf8_unicode_ci', length=3), nullable=True))
    op.add_column('transactions', sa.Column('amount_sent_krw', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('amount_received_krw', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_ibfk_2', 'transactions', 'currencies', ['currency_code'], ['code'])
    op.create_foreign_key('transactions_ibfk_4', 'transactions', 'payment_methods', ['payment_method_id'], ['id'])
    op.create_foreign_key('transactions_ibfk_1', 'transactions', 'users', ['changed_by_id'], ['id'])
    op.drop_column('transactions', 'customer_id')
    op.drop_column('transactions', 'amount')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'payment_method_id')
    op.create_table('transactions_orders',
    sa.Column('transaction_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_id', mysql.VARCHAR(collation='utf8_unicode_ci', length=16), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='transactions_orders_ibfk_1'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name='transactions_orders_ibfk_2'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('payments_orders')
    op.drop_index(op.f('ix_payments_when_created'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
