"""zip length 15

Revision ID: 5053d16e8bb6
Revises: 7316280011ae
Create Date: 2021-06-27 13:34:37.253424

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5053d16e8bb6'
down_revision = '7316280011ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_boxes_when_created', table_name='boxes')
    # op.drop_table('boxes')
    op.alter_column('orders', 'zip',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=10),
               type_=sa.String(length=15),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'zip',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=10),
               existing_nullable=True)
    op.create_table('boxes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('when_created', mysql.DATETIME(), nullable=True),
    sa.Column('when_changed', mysql.DATETIME(), nullable=True),
    sa.Column('length', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('width', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('height', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weight', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_boxes_when_created', 'boxes', ['when_created'], unique=False)
    # ### end Alembic commands ###
