"""order - creation time

Revision ID: 521220e017ed
Revises: a550987b06fd
Create Date: 2020-07-18 22:48:53.679803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '521220e017ed'
down_revision = 'a550987b06fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('time_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'time_created')
    # ### end Alembic commands ###
