"""warehouse purchase orders

Revision ID: 53976c05eb99
Revises: 29831cf444c0
Create Date: 2022-04-15 14:49:32.382639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53976c05eb99'
down_revision = '29831cf444c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_order_warehouses',
    sa.Column('when_created', sa.DateTime(), nullable=True),
    sa.Column('when_changed', sa.DateTime(), nullable=True),
    sa.Column('purchase_order_id', sa.String(length=23), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('purchase_order_id')
    )
    op.create_index(op.f('ix_purchase_order_warehouses_when_created'), 'purchase_order_warehouses', ['when_created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_order_warehouses_when_created'), table_name='purchase_order_warehouses')
    op.drop_table('purchase_order_warehouses')
    # ### end Alembic commands ###
