"""currency symbols

Revision ID: 53c48d1fdab3
Revises: fa6736e5137e
Create Date: 2021-04-02 08:48:20.738518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53c48d1fdab3'
down_revision = 'fa6736e5137e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currencies', sa.Column('prefix', sa.String(length=1), nullable=True))
    op.add_column('currencies', sa.Column('suffix', sa.String(length=1), nullable=True))
    op.execute('UPDATE currencies SET prefix=\'₩\' WHERE code=\'KRW\'')
    op.execute('UPDATE currencies SET prefix=\'$\' WHERE code=\'USD\'')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currencies', 'suffix')
    op.drop_column('currencies', 'prefix')
    # ### end Alembic commands ###
