"""pv stats

Revision ID: 543be56f2401
Revises: b7d4a8688f67
Create Date: 2021-11-21 13:16:40.976431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '543be56f2401'
down_revision = 'b7d4a8688f67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('alter table pv_stats_permissions drop constraint pv_stats_permissions_ibfk_1')
    op.execute('alter table pv_stats_permissions drop primary key')
    op.execute('alter table pv_stats_permissions add column id integer auto_increment primary key')
    op.execute('alter table pv_stats_permissions add constraint pv_stats_permissions_ibfk_1 foreign key (user_id) references users (id)')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pv_stats_permissions', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('pv_stats_permissions', 'node_id',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=8),
               nullable=False)
    op.drop_column('pv_stats_permissions', 'id')
    # ### end Alembic commands ###
