"""vendor_id for Product

Revision ID: 54b6dfefd613
Revises: 
Create Date: 2023-12-19 19:14:46.044253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54b6dfefd613'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_orders',
    sa.Column('when_created', sa.DateTime(), nullable=True),
    sa.Column('when_changed', sa.DateTime(), nullable=True),
    sa.Column('order_id', sa.String(length=16), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_warehouse_orders_when_created'), 'warehouse_orders', ['when_created'], unique=False)
    op.alter_column('dhl_countries', 'country_id',
               existing_type=mysql.VARCHAR(length=2),
               nullable=False)
    op.drop_constraint('dhl_countries_ibfk_2', 'dhl_countries', type_='foreignkey')
    op.alter_column('dhl_rates', 'zone',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('dhl_rates', 'weight',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.drop_constraint('dhl_rates_ibfk_1', 'dhl_rates', type_='foreignkey')
    op.alter_column('dhl_zones', 'id', existing_type=mysql.INTEGER(), 
                    new_column_name='zone', nullable=False)
    op.alter_column('order_packers', 'packer',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.drop_column('order_products', 'subcustomer')
    op.alter_column('order_products_warehouses', 'order_product_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('products', sa.Column('vendor_id', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_products_vendor_id'), 'products', ['vendor_id'], unique=False)
    op.alter_column('products_shipping', 'product_id',
               existing_type=mysql.VARCHAR(length=16),
               nullable=True)
    op.alter_column('pv_stats_permissions', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('shipping_rates', 'rate',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key(None, 'dhl_countries', 'dhl_zones', ['zone'], ['zone'])
    op.create_foreign_key(None, 'dhl_rates', 'dhl_zones', ['zone'], ['zone'])
    op.create_foreign_key(None, 'network_nodes', 'network_nodes', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'countries', ['country_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipping_rates', 'rate',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('shipping', 'name',
               existing_type=sa.String(length=16),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_unicode_ci', length=32),
               existing_nullable=True)
    op.alter_column('pv_stats_permissions', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('products_shipping', 'product_id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_unicode_ci', length=16),
               nullable=False)
    op.drop_index(op.f('ix_products_vendor_id'), table_name='products')
    op.drop_column('products', 'vendor_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.alter_column('orders', 'comment',
               existing_type=sa.String(length=128),
               type_=mysql.TEXT(charset='utf8mb3', collation='utf8mb3_unicode_ci'),
               existing_nullable=True)
    op.alter_column('order_products_warehouses', 'order_product_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.add_column('order_products', sa.Column('subcustomer', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_unicode_ci', length=256), nullable=True))
    op.drop_index(op.f('ix_order_packers_when_created'), table_name='order_packers')
    op.alter_column('order_packers', 'packer',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.drop_constraint(None, 'network_nodes', type_='foreignkey')
    op.add_column('dhl_zones', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('dhl_zones', 'zone')
    op.drop_constraint(None, 'dhl_rates', type_='foreignkey')
    op.create_foreign_key('dhl_rates_ibfk_1', 'dhl_rates', 'dhl_zones', ['zone'], ['id'])
    op.alter_column('dhl_rates', 'weight',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('dhl_rates', 'zone',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'dhl_countries', type_='foreignkey')
    op.create_foreign_key('dhl_countries_ibfk_2', 'dhl_countries', 'dhl_zones', ['zone'], ['id'])
    op.alter_column('dhl_countries', 'country_id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_unicode_ci', length=2),
               nullable=True)
    op.create_table('tmp',
    sa.Column('id', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_unicode_ci', length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb3_unicode_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('temp',
    sa.Column('dst', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_unicode_ci', length=2), nullable=True),
    sa.Column('rate', mysql.INTEGER(), autoincrement=False, nullable=True),
    mysql_collate='utf8mb3_unicode_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_warehouse_orders_when_created'), table_name='warehouse_orders')
    op.drop_table('warehouse_orders')
    # ### end Alembic commands ###
