"""suborder order_id

Revision ID: 5688f352e8d6
Revises: e2fe6a48bd5f
Create Date: 2020-11-18 08:53:21.541862

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5688f352e8d6'
down_revision = 'e2fe6a48bd5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        DELETE FROM op, s
        USING suborders AS s JOIN order_products AS op ON s.id = op.suborder_id
        WHERE s.order_id IS NULL""")
    op.alter_column('payment_methods', 'name',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=16),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('suborders', 'order_id',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=16),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suborders', 'order_id',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=16),
               nullable=True)
    op.alter_column('payment_methods', 'name',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(collation='utf8_unicode_ci', length=16),
               existing_nullable=True)
    # ### end Alembic commands ###
