"""product shipping

Revision ID: 56cb08719d24
Revises: f22c2a205ef2
Create Date: 2021-03-16 14:04:32.799153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56cb08719d24'
down_revision = 'f22c2a205ef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_shipping',
    sa.Column('product_id', sa.String(length=16), nullable=True),
    sa.Column('shipping_method_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['shipping_method_id'], ['shipping.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products_shipping')
    # ### end Alembic commands ###
