"""Settings

Revision ID: 5a9f34337673
Revises: 38a88184571b
Create Date: 2021-02-08 20:20:56.421675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a9f34337673'
down_revision = '38a88184571b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
        sa.Column('when_created', sa.DateTime(), nullable=True),
        sa.Column('when_changed', sa.DateTime(), nullable=True),
        sa.Column('key', sa.String(length=64), nullable=False),
        sa.Column('value', sa.String(length=128), nullable=True),
        sa.Column('default_value', sa.String(length=128), nullable=True),
        sa.Column('description', sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_settings_when_created'), 'settings', ['when_created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_when_created'), table_name='settings')
    op.drop_table('settings')
    # ### end Alembic commands ###
