"""Base currency

Revision ID: 5b0c669c7fb8
Revises: 63097ee4fc86
Create Date: 2025-12-18 21:53:27.069778

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b0c669c7fb8'
down_revision = '63097ee4fc86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currencies', sa.Column('base', sa.Boolean(), nullable=False, server_default='0'))
    op.execute("UPDATE currencies SET base = 1 WHERE code = 'KRW'")
    op.add_column('countries', sa.Column('currency_code', sa.String(length=3), nullable=True))
    op.add_column('countries', sa.Column('locale', sa.String(length=5), nullable=True))
    op.execute("UPDATE countries SET currency_code = 'KRW', locale = 'ko-KR' WHERE code = 'KR'")
    op.execute("UPDATE countries SET currency_code = 'USD', locale = 'en-US' WHERE code = 'US'")
    op.execute("UPDATE countries SET currency_code = 'EUR', locale = 'de-DE' WHERE code = 'DE'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currencies', 'base')
    op.drop_column('countries', 'locale')
    op.drop_column('countries', 'currency_code')
    # ### end Alembic commands ###
