"""order statuses

Revision ID: 5f479faf462c
Revises: 9f910536bfed
Create Date: 2021-02-26 12:05:19.555770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f479faf462c'
down_revision = '9f910536bfed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=mysql.ENUM('pending', 'can_be_paid', 'po_created', 'paid', 'shipped', 'complete', collation='utf8_unicode_ci'),
               type_=sa.Enum('pending', 'can_be_paid', 'po_created', 'packed', 'shipped', 'cancelled', name='orderstatus'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('pending', 'can_be_paid', 'po_created', 'packed', 'shipped', 'cancelled', name='orderstatus'),
               type_=mysql.ENUM('pending', 'can_be_paid', 'po_created', 'paid', 'shipped', 'complete', collation='utf8_unicode_ci'),
               existing_nullable=True)
    # ### end Alembic commands ###
