"""Add user_id to invoices

Revision ID: 63097ee4fc86
Revises: 9a9e11c72d3c
Create Date: 2025-12-14 14:17:11.170166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63097ee4fc86'
down_revision = '9a9e11c72d3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Populate user_id for existing invoices based on first order's user
    op.add_column('invoices', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_invoices_user_id', 'invoices', 'users', ['user_id'], ['id'])
    op.execute("""
        UPDATE invoices SET user_id = (
            SELECT u.id FROM users AS u
            WHERE username = 'admin' LIMIT 1
        ) WHERE user_id IS NULL
    """)
    op.alter_column('invoices', 'user_id', existing_type=sa.Integer(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_invoices_user_id', 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'user_id')
    # ### end Alembic commands ###
