"""products table change id type

Revision ID: 63a5835e3bb0
Revises: 55f0ba17ec8c
Create Date: 2020-07-16 11:53:33.529102

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63a5835e3bb0'
down_revision = '55f0ba17ec8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('id', sa.String(length=64), nullable=False))
    op.drop_column('products', 'product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_id', mysql.VARCHAR(collation='utf8_unicode_ci', length=64), nullable=False))
    op.drop_column('products', 'id')
    # ### end Alembic commands ###
