"""address english

Revision ID: 675c8fc36c31
Revises: 3791f8b3e6e2
Create Date: 2021-07-10 20:37:28.520307

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '675c8fc36c31'
down_revision = '3791f8b3e6e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('address_1_eng', sa.String(length=65), nullable=True))
    op.add_column('addresses', sa.Column('address_2_eng', sa.String(length=65), nullable=True))
    op.add_column('addresses', sa.Column('city_eng', sa.String(length=65), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'city_eng')
    op.drop_column('addresses', 'address_2_eng')
    op.drop_column('addresses', 'address_1_eng')
    # ### end Alembic commands ###
