"""currency history

Revision ID: 681e38804a30
Revises: 53c48d1fdab3
Create Date: 2021-04-02 09:20:26.772010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '681e38804a30'
down_revision = '53c48d1fdab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('when_created', sa.DateTime(), nullable=True),
        sa.Column('when_changed', sa.DateTime(), nullable=True),
        sa.Column('code', sa.String(length=3), nullable=True),
        sa.Column('rate', sa.Numeric(scale=5), nullable=True),
        sa.ForeignKeyConstraint(['code'], ['currencies.code'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currency_history_when_created'), 'currency_history', ['when_created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currency_history_when_created'), table_name='currency_history')
    op.drop_table('currency_history')
    # ### end Alembic commands ###
