"""order product comments

Revision ID: 6f580c7626c4
Revises: d93101c9c39c
Create Date: 2020-07-23 20:46:53.559948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f580c7626c4'
down_revision = 'd93101c9c39c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_products', sa.Column('changed_at', sa.DateTime(), nullable=True))
    op.add_column('order_products', sa.Column('private_comment', sa.String(length=256), nullable=True))
    op.add_column('order_products', sa.Column('public_comment', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_order_products_changed_at'), 'order_products', ['changed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_products_changed_at'), table_name='order_products')
    op.drop_column('order_products', 'public_comment')
    op.drop_column('order_products', 'private_comment')
    op.drop_column('order_products', 'changed_at')
    # ### end Alembic commands ###
