"""suborder new id

Revision ID: 716b2b1f0be6
Revises: 09d4caed252e
Create Date: 2020-10-22 23:03:35.168037

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '716b2b1f0be6'
down_revision = '09d4caed252e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_products_ibfk_3', 'order_products', type_='foreignkey')
    op.drop_constraint('purchase_orders_ibfk_2', 'purchase_orders', type_='foreignkey')
    op.alter_column('suborders', 'id', nullable=False,
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=20))
    op.alter_column('order_products', 'suborder_id', nullable=False,
                existing_type=mysql.INTEGER(),
                type_=sa.String(length=20))
    op.alter_column('purchase_orders', 'suborder_id', nullable=False,
                existing_type=mysql.INTEGER(),
                type_=sa.String(length=20))
    op.create_foreign_key('order_products_ibfk_3', 'order_products', 'suborders',
                ['suborder_id'], ['id'])
    op.create_foreign_key('purchase_orders_ibfk_2', 'purchase_orders', 'suborders',
                ['suborder_id'], ['id'])
    op.add_column('suborders', sa.Column('seq_num', sa.Integer(), nullable=True))
    op.execute("UPDATE suborders SET seq_num = 0")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_products_ibfk_3', 'order_products', type_='foreignkey')
    op.drop_constraint('purchase_orders_ibfk_2', 'purchase_orders', type_='foreignkey')
    op.alter_column('suborders', 'id',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER())
    op.alter_column('order_products', 'suborder_id',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER())
    op.alter_column('purchase_orders', 'suborder_id',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER())
    op.create_foreign_key('order_products_ibfk_3', 'order_products', 'suborders',
                ['suborder_id'], ['id'])
    op.create_foreign_key('purchase_orders_ibfk_2', 'purchase_orders', 'suborders',
                ['suborder_id'], ['id'])
    op.drop_column('suborders', 'seq_num')
    # ### end Alembic commands ###
