"""pv_stats

Revision ID: 72d51a812c18
Revises: 088a8133b78b
Create Date: 2021-12-26 20:21:37.121120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72d51a812c18'
down_revision = '088a8133b78b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pv_stats_permissions', sa.Column('is_being_updated', sa.Boolean(), nullable=True))
    op.execute('UPDATE pv_stats_permissions SET is_being_updated = 0')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pv_stats_permissions', 'is_being_updated')
    # ### end Alembic commands ###
