"""order total weight

Revision ID: 7316280011ae
Revises: a574c2f976c8
Create Date: 2021-06-26 17:25:43.850475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7316280011ae'
down_revision = 'a574c2f976c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total_weight_set_manually', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'total_weight_set_manually')
    # ### end Alembic commands ###
