"""order edit

Revision ID: 73ae738c75c9
Revises: c7ff9e010f0b
Create Date: 2020-09-21 11:14:24.134371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '73ae738c75c9'
down_revision = 'c7ff9e010f0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_buyout_date', table_name='orders')
    op.drop_column('orders', 'buyout_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('buyout_date', mysql.DATETIME(), nullable=True))
    op.create_index('ix_orders_buyout_date', 'orders', ['buyout_date'], unique=False)
    # ### end Alembic commands ###
