"""product synchronize

Revision ID: 74595706728d
Revises: 73ae738c75c9
Create Date: 2020-09-23 14:26:07.745959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74595706728d'
down_revision = '73ae738c75c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('synchronize', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_products_when_created'), 'products', ['when_created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_when_created'), table_name='products')
    op.drop_column('products', 'synchronize')
    # ### end Alembic commands ###
