"""vendor -> company

Revision ID: 75e1827e3062
Revises: a50a4a4775ca
Create Date: 2020-10-09 21:38:30.124448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75e1827e3062'
down_revision = 'a50a4a4775ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('when_created', sa.DateTime(), nullable=True),
    sa.Column('when_changed', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('tax_id_1', sa.Integer(), nullable=True),
    sa.Column('tax_id_2', sa.Integer(), nullable=True),
    sa.Column('tax_id_3', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=13), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_when_created'), 'companies', ['when_created'], unique=False)
    op.drop_index('ix_vendors_when_created', table_name='vendors')
    op.drop_table('vendors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('when_created', mysql.DATETIME(), nullable=True),
    sa.Column('when_changed', mysql.DATETIME(), nullable=True),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=32), nullable=True),
    sa.Column('tax_id_1', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tax_id_2', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tax_id_3', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('phone', mysql.VARCHAR(collation='utf8_unicode_ci', length=13), nullable=True),
    sa.Column('address_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], name='vendors_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_vendors_when_created', 'vendors', ['when_created'], unique=False)
    op.drop_index(op.f('ix_companies_when_created'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
