"""Network nodes

Revision ID: 765bc51caf4e
Revises: 0c23042cff7f
Create Date: 2021-02-20 13:57:10.657557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '765bc51caf4e'
down_revision = '0c23042cff7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('network_nodes', sa.Column('center', sa.String(length=32), nullable=True))
    op.add_column('network_nodes', sa.Column('country', sa.String(length=32), nullable=True))
    op.add_column('network_nodes', sa.Column('highest_rank', sa.String(length=16), nullable=True))
    op.add_column('network_nodes', sa.Column('name', sa.String(length=32), nullable=True))
    op.add_column('network_nodes', sa.Column('network_pv', sa.Integer(), nullable=True))
    op.add_column('network_nodes', sa.Column('pv', sa.Integer(), nullable=True))
    op.add_column('network_nodes', sa.Column('rank', sa.String(length=16), nullable=True))
    op.add_column('network_nodes', sa.Column('signup_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_network_nodes_rank'), 'network_nodes', ['rank'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_network_nodes_rank'), table_name='network_nodes')
    op.drop_column('network_nodes', 'signup_date')
    op.drop_column('network_nodes', 'rank')
    op.drop_column('network_nodes', 'pv')
    op.drop_column('network_nodes', 'network_pv')
    op.drop_column('network_nodes', 'name')
    op.drop_column('network_nodes', 'highest_rank')
    op.drop_column('network_nodes', 'country')
    op.drop_column('network_nodes', 'center')
    # ### end Alembic commands ###
