"""order - phone

Revision ID: 78690a8ed199
Revises: 521220e017ed
Create Date: 2020-07-20 10:01:39.324007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '78690a8ed199'
down_revision = '521220e017ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'phone',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'phone',
               existing_type=sa.String(length=32),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
