"""company contact person

Revision ID: 7b5e946d0a00
Revises: 9ec8d92aeed8
Create Date: 2021-03-05 19:45:42.523914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b5e946d0a00'
down_revision = '9ec8d92aeed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('contact_person', sa.String(length=64), nullable=True))
    op.execute("INSERT INTO products (id, name, weight, available, synchronize, separate_shipping, purchase) VALUES ('SHIPPING', 'Shipping', 0, 0, 0, 0, 0)")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'contact_person')
    # ### end Alembic commands ###
