"""sale order purchase date

Revision ID: 7d59f47a0119
Revises: c3c22990455c
Create Date: 2020-11-29 20:24:38.461883

"""
from datetime import datetime
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d59f47a0119'
down_revision = 'c3c22990455c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column(
        'purchase_date_sort', sa.DateTime(), nullable=False, 
        server_default='9999-12-31'))
    op.create_index(op.f('ix_orders_purchase_date_sort'), 'orders', ['purchase_date_sort'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_purchase_date_sort'), table_name='orders')
    op.drop_column('orders', 'purchase_date_sort')
    # ### end Alembic commands ###
