"""Increase subcustomer password length

Revision ID: 7ff1596fc096
Revises: c01aefec05ef
Create Date: 2021-02-19 15:27:42.165155

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ff1596fc096'
down_revision = 'c01aefec05ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subcustomers', 'password',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=16),
               type_=sa.String(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subcustomers', 'password',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(collation='utf8_unicode_ci', length=16),
               existing_nullable=True)
    # ### end Alembic commands ###
