"""new PO implementation

Revision ID: 8090c06d2b01
Revises: 98d8ca44873f
Create Date: 2023-01-05 12:37:23.256152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8090c06d2b01'
down_revision = '98d8ca44873f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_orders', 'vendor_po_id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_unicode_ci', length=12),
               type_=sa.String(length=18),
               existing_nullable=True)
    op.alter_column('purchase_orders', 'status',
               existing_type=mysql.ENUM('pending', 'posted', 'paid', 'delivered', 'failed', 'partially_posted', 'payment_past_due', 'shipped', 'cancelled', charset='utf8mb3', collation='utf8mb3_unicode_ci'),
               type_=sa.Enum('pending', 'partially_posted', 'posted', 'paid', 'payment_past_due', 'shipped', 'delivered', 'failed', 'cancelled', name='purchaseorderstatus'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_orders', 'status',
               existing_type=sa.Enum('pending', 'partially_posted', 'posted', 'paid', 'payment_past_due', 'shipped', 'delivered', 'failed', 'cancelled', name='purchaseorderstatus'),
               type_=mysql.ENUM('pending', 'posted', 'paid', 'delivered', 'failed', 'partially_posted', 'payment_past_due', 'shipped', 'cancelled', charset='utf8mb3', collation='utf8mb3_unicode_ci'),
               existing_nullable=True)
    op.alter_column('purchase_orders', 'vendor_po_id',
               existing_type=sa.String(length=18),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_unicode_ci', length=12),
               existing_nullable=True)
    # ### end Alembic commands ###
