"""suborder

Revision ID: 80e26191e826
Revises: b403db478ec4
Create Date: 2020-09-18 17:49:52.906184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '80e26191e826'
down_revision = 'b403db478ec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcustomers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('when_created', sa.DateTime(), nullable=True),
    sa.Column('when_changed', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=16), nullable=True),
    sa.Column('password', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcustomers_when_created'), 'subcustomers', ['when_created'], unique=False)
    op.create_table('suborders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('when_created', sa.DateTime(), nullable=True),
    sa.Column('when_changed', sa.DateTime(), nullable=True),
    sa.Column('subcustomer_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.String(length=16), nullable=True),
    sa.Column('buyout_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['subcustomer_id'], ['subcustomers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suborders_buyout_date'), 'suborders', ['buyout_date'], unique=False)
    op.create_index(op.f('ix_suborders_when_created'), 'suborders', ['when_created'], unique=False)
    op.add_column('order_products', sa.Column('suborder_id', sa.Integer(), nullable=True))
    op.add_column('order_products', sa.Column('when_created', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_order_products_when_created'), 'order_products', ['when_created'], unique=False)
    op.drop_index('ix_order_products_when_changed', table_name='order_products')
    op.create_foreign_key(None, 'order_products', 'suborders', ['suborder_id'], ['id'])
    op.drop_column('order_products', 'subcustomer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_products', sa.Column('subcustomer', mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=256), nullable=True))
    op.drop_constraint(None, 'order_products', type_='foreignkey')
    op.create_index('ix_order_products_when_changed', 'order_products', ['when_changed'], unique=False)
    op.drop_index(op.f('ix_order_products_when_created'), table_name='order_products')
    op.drop_column('order_products', 'when_created')
    op.drop_column('order_products', 'suborder_id')
    op.drop_index(op.f('ix_suborders_when_created'), table_name='suborders')
    op.drop_index(op.f('ix_suborders_buyout_date'), table_name='suborders')
    op.drop_table('suborders')
    op.drop_index(op.f('ix_subcustomers_when_created'), table_name='subcustomers')
    op.drop_table('subcustomers')
    # ### end Alembic commands ###
