"""invoice items to usd

Revision ID: 827efe43c06c
Revises: 7dbbe10c7ebb
Create Date: 2020-09-11 07:34:36.584645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '827efe43c06c'
down_revision = '7dbbe10c7ebb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoice_items', 'price',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(precision=8, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoice_items', 'price',
               existing_type=sa.Numeric(scale=2),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
