"""shipping

Revision ID: 843f63adf3b9
Revises: 9366c0b02715
Create Date: 2020-08-15 21:51:07.407310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '843f63adf3b9'
down_revision = '9366c0b02715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('when_created', sa.DateTime(), nullable=True),
    sa.Column('when_changed', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipping_when_created'), 'shipping', ['when_created'], unique=False)
    op.add_column('shipping_rates', sa.Column('shipping_method_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shipping_rates', 'shipping', ['shipping_method_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipping_rates', type_='foreignkey')
    op.drop_column('shipping_rates', 'shipping_method_id')
    op.drop_index(op.f('ix_shipping_when_created'), table_name='shipping')
    op.drop_table('shipping')
    # ### end Alembic commands ###
