"""float->numeric

Revision ID: 862d9c698757
Revises: 078fe3bb3fe2
Create Date: 2020-07-28 15:53:21.111992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '862d9c698757'
down_revision = '078fe3bb3fe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('time_created', sa.DateTime(), nullable=True))
    op.drop_column('orders', 'when_created')
    op.alter_column('transactions', 'amount_original',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(scale=2),
               existing_nullable=True)
    op.drop_column('transactions', 'changed_at')
    op.drop_column('transactions', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('transactions', sa.Column('changed_at', mysql.DATETIME(), nullable=True))
    op.alter_column('transactions', 'amount_original',
               existing_type=sa.Numeric(scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.add_column('orders', sa.Column('when_created', mysql.DATETIME(), nullable=True))
    op.drop_column('orders', 'time_created')
    # ### end Alembic commands ###
