"""PO adress

Revision ID: 8a808621504d
Revises: 4bad9cf69f5f
Create Date: 2021-07-11 08:28:04.899376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a808621504d'
down_revision = '4bad9cf69f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('delivery_comment', sa.Text(), nullable=True))
    op.add_column('purchase_orders', sa.Column('address_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchase_orders', 'addresses', ['address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_column('purchase_orders', 'address_id')
    op.drop_column('addresses', 'delivery_comment')
    # ### end Alembic commands ###
