"""PO when posted

Revision ID: 8c9957eafdb4
Revises: f3e2e50e0c92
Create Date: 2021-04-08 11:41:48.218994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c9957eafdb4'
down_revision = 'f3e2e50e0c92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('when_posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'when_posted')
    # ### end Alembic commands ###
