"""add country first zip

Revision ID: 8e6aa0006bd6
Revises: 9cdea7e8e1b2
Create Date: 2024-11-01 12:00:40.713533

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e6aa0006bd6'
down_revision = '9cdea7e8e1b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('first_zip', sa.String(length=9), nullable=True))
    op.execute("UPDATE countries SET first_zip='AD100' WHERE id='AD'")
    op.execute("UPDATE countries SET first_zip='1601' WHERE id='AR'")
    op.execute("UPDATE countries SET first_zip='96799' WHERE id='AS'")
    op.execute("UPDATE countries SET first_zip='1010' WHERE id='AT'")
    op.execute("UPDATE countries SET first_zip='200' WHERE id='AU'")
    op.execute("UPDATE countries SET first_zip='22100' WHERE id='AX'")
    op.execute("UPDATE countries SET first_zip='AZ 0100' WHERE id='AZ'")
    op.execute("UPDATE countries SET first_zip='1000' WHERE id='BD'")
    op.execute("UPDATE countries SET first_zip='1000' WHERE id='BE'")
    op.execute("UPDATE countries SET first_zip='1000' WHERE id='BG'")
    op.execute("UPDATE countries SET first_zip='CR 01' WHERE id='BM'")
    op.execute("UPDATE countries SET first_zip='01000-000' WHERE id='BR'")
    op.execute("UPDATE countries SET first_zip='210000' WHERE id='BY'")
    op.execute("UPDATE countries SET first_zip='A0A' WHERE id='CA'")
    op.execute("UPDATE countries SET first_zip='1000' WHERE id='CH'")
    op.execute("UPDATE countries SET first_zip='1000000' WHERE id='CL'")
    op.execute("UPDATE countries SET first_zip='10000' WHERE id='CN'")
    op.execute("UPDATE countries SET first_zip='50001' WHERE id='CO'")
    op.execute("UPDATE countries SET first_zip='10101' WHERE id='CR'")
    op.execute("UPDATE countries SET first_zip='1010' WHERE id='CY'")
    op.execute("UPDATE countries SET first_zip='100 00' WHERE id='CZ'")
    op.execute("UPDATE countries SET first_zip='1067' WHERE id='DE'")
    op.execute("UPDATE countries SET first_zip='800' WHERE id='DK'")
    op.execute("UPDATE countries SET first_zip='10101' WHERE id='DO'")
    op.execute("UPDATE countries SET first_zip='1000' WHERE id='DZ'")
    op.execute("UPDATE countries SET first_zip='10101' WHERE id='EC'")
    op.execute("UPDATE countries SET first_zip='10001' WHERE id='EE'")
    op.execute("UPDATE countries SET first_zip='1001' WHERE id='ES'")
    op.execute("UPDATE countries SET first_zip='2' WHERE id='FI'")
    op.execute("UPDATE countries SET first_zip='96941' WHERE id='FM'")
    op.execute("UPDATE countries SET first_zip='100' WHERE id='FO'")
    op.execute("UPDATE countries SET first_zip='1000' WHERE id='FR'")
    op.execute("UPDATE countries SET first_zip='AB10' WHERE id='GB'")
    op.execute("UPDATE countries SET first_zip='97300' WHERE id='GF'")
    op.execute("UPDATE countries SET first_zip='GY1' WHERE id='GG'")
    op.execute("UPDATE countries SET first_zip='2412' WHERE id='GL'")
    op.execute("UPDATE countries SET first_zip='97001' WHERE id='GP'")
    op.execute("UPDATE countries SET first_zip='104 31' WHERE id='GR'")
    op.execute("UPDATE countries SET first_zip='1001' WHERE id='GT'")
    op.execute("UPDATE countries SET first_zip='96910' WHERE id='GU'")
    op.execute("UPDATE countries SET first_zip='10000' WHERE id='HR'")
    op.execute("UPDATE countries SET first_zip='HT1110' WHERE id='HT'")
    op.execute("UPDATE countries SET first_zip='1007' WHERE id='HU'")
    op.execute("UPDATE countries SET first_zip='A41' WHERE id='IE'")
    op.execute("UPDATE countries SET first_zip='IM1' WHERE id='IM'")
    op.execute("UPDATE countries SET first_zip='110001' WHERE id='IN'")
    op.execute("UPDATE countries SET first_zip='101' WHERE id='IS'")
    op.execute("UPDATE countries SET first_zip='10' WHERE id='IT'")
    op.execute("UPDATE countries SET first_zip='JE1' WHERE id='JE'")
    op.execute("UPDATE countries SET first_zip='001-0000' WHERE id='JP'")
    op.execute("UPDATE countries SET first_zip='1000' WHERE id='KR'")
    op.execute("UPDATE countries SET first_zip='9485' WHERE id='LI'")
    op.execute("UPDATE countries SET first_zip='100' WHERE id='LK'")
    op.execute("UPDATE countries SET first_zip='1' WHERE id='LT'")
    op.execute("UPDATE countries SET first_zip='L-1111' WHERE id='LU'")
    op.execute("UPDATE countries SET first_zip='LV-1001' WHERE id='LV'")
    op.execute("UPDATE countries SET first_zip='11022' WHERE id='MA'")
    op.execute("UPDATE countries SET first_zip='98000' WHERE id='MC'")
    op.execute("UPDATE countries SET first_zip='MD-2000' WHERE id='MD'")
    op.execute("UPDATE countries SET first_zip='96960' WHERE id='MH'")
    op.execute("UPDATE countries SET first_zip='1000' WHERE id='MK'")
    op.execute("UPDATE countries SET first_zip='96950' WHERE id='MP'")
    op.execute("UPDATE countries SET first_zip='97200' WHERE id='MQ'")
    op.execute("UPDATE countries SET first_zip='ATD' WHERE id='MT'")
    op.execute("UPDATE countries SET first_zip='101100' WHERE id='MW'")
    op.execute("UPDATE countries SET first_zip='1000' WHERE id='MX'")
    op.execute("UPDATE countries SET first_zip='1000' WHERE id='MY'")
    op.execute("UPDATE countries SET first_zip='98800' WHERE id='NC'")
    op.execute("UPDATE countries SET first_zip='1011' WHERE id='NL'")
    op.execute("UPDATE countries SET first_zip='1' WHERE id='NO'")
    op.execute("UPDATE countries SET first_zip='110' WHERE id='NZ'")
    op.execute("UPDATE countries SET first_zip='1001' WHERE id='PA'")
    op.execute("UPDATE countries SET first_zip='1000' WHERE id='PE'")
    op.execute("UPDATE countries SET first_zip='98701' WHERE id='PF'")
    op.execute("UPDATE countries SET first_zip='400' WHERE id='PH'")
    op.execute("UPDATE countries SET first_zip='10010' WHERE id='PK'")
    op.execute("UPDATE countries SET first_zip='00-002' WHERE id='PL'")
    op.execute("UPDATE countries SET first_zip='97500' WHERE id='PM'")
    op.execute("UPDATE countries SET first_zip='601' WHERE id='PR'")
    op.execute("UPDATE countries SET first_zip='1000-001' WHERE id='PT'")
    op.execute("UPDATE countries SET first_zip='96940' WHERE id='PW'")
    op.execute("UPDATE countries SET first_zip='97400' WHERE id='RE'")
    op.execute("UPDATE countries SET first_zip='10011' WHERE id='RO'")
    op.execute("UPDATE countries SET first_zip='11000' WHERE id='RS'")
    op.execute("UPDATE countries SET first_zip='101000' WHERE id='RU'")
    op.execute("UPDATE countries SET first_zip='100 04' WHERE id='SE'")
    op.execute("UPDATE countries SET first_zip='18906' WHERE id='SG'")
    op.execute("UPDATE countries SET first_zip='1000' WHERE id='SI'")
    op.execute("UPDATE countries SET first_zip='8099' WHERE id='SJ'")
    op.execute("UPDATE countries SET first_zip='010 01' WHERE id='SK'")
    op.execute("UPDATE countries SET first_zip='47890' WHERE id='SM'")
    op.execute("UPDATE countries SET first_zip='10100' WHERE id='TH'")
    op.execute("UPDATE countries SET first_zip='1010' WHERE id='TR'")
    op.execute("UPDATE countries SET first_zip='1001' WHERE id='UA'")
    op.execute("UPDATE countries SET first_zip='501' WHERE id='US'")
    op.execute("UPDATE countries SET first_zip='11000' WHERE id='UY'")
    op.execute("UPDATE countries SET first_zip='120' WHERE id='VA'")
    op.execute("UPDATE countries SET first_zip='801' WHERE id='VI'")
    op.execute("UPDATE countries SET first_zip='98600' WHERE id='WF'")
    op.execute("UPDATE countries SET first_zip='97600' WHERE id='YT'")
    op.execute("UPDATE countries SET first_zip='2' WHERE id='ZA'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('countries', 'first_zip')
    # ### end Alembic commands ###
