"""transaction extend

Revision ID: 9366c0b02715
Revises: 4a008c28ebf0
Create Date: 2020-08-13 12:08:39.347853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9366c0b02715'
down_revision = '4a008c28ebf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('order_id', sa.String(length=16), nullable=True))
    op.add_column('transactions', sa.Column('payment_method', sa.String(length=16), nullable=True))
    op.create_foreign_key(None, 'transactions', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'payment_method')
    op.drop_column('transactions', 'order_id')
    # ### end Alembic commands ###
