"""when-

Revision ID: 940776d04edb
Revises: 862d9c698757
Create Date: 2020-07-28 16:11:58.088953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940776d04edb'
down_revision = '862d9c698757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('when_changed', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('when_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'when_created')
    op.drop_column('products', 'when_changed')
    # ### end Alembic commands ###
