"""order product

Revision ID: 966e779b4f54
Revises: d15275bc51d4
Create Date: 2020-09-02 19:25:35.354602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '966e779b4f54'
down_revision = 'd15275bc51d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_products_changed_at', table_name='order_products')
    op.alter_column('order_products', 'changed_at',
                existing_type=mysql.DATETIME(),
                new_column_name='when_changed')    
    op.create_index(op.f('ix_order_products_when_changed'), 'order_products',
                    ['when_changed'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_products_when_changed'), table_name='order_products')
    op.alter_column('order_products', 'when_changed',
                existing_type=mysql.DATETIME(),
                new_column_name='changed_at')
    op.create_index('ix_order_products_changed_at', 'order_products', ['changed_at'], unique=False)
    # ### end Alembic commands ###
