"""payment additional info

Revision ID: 9819add7f80f
Revises: 4fd1a41b0133
Create Date: 2021-01-20 07:53:15.096687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9819add7f80f'
down_revision = '4fd1a41b0133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'country_id')
    op.drop_column('invoices', 'address')
    op.drop_column('invoices', 'phone')
    op.alter_column('order_products', 'status',
               existing_type=mysql.SET(collation='utf8_unicode_ci', length=11),
               type_=sa.Enum('pending', 'po_created', 'unavailable', 'purchased', 'shipped', name='orderproductstatus'),
               existing_nullable=True)
    op.add_column('payments', sa.Column('additional_info', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'additional_info')
    op.alter_column('order_products', 'status',
               existing_type=sa.Enum('pending', 'po_created', 'unavailable', 'purchased', 'shipped', name='orderproductstatus'),
               type_=mysql.SET(collation='utf8_unicode_ci', length=11),
               existing_nullable=True)
    op.add_column('invoices', sa.Column('phone', mysql.VARCHAR(collation='utf8_unicode_ci', length=64), nullable=True))
    op.add_column('invoices', sa.Column('address', mysql.VARCHAR(collation='utf8_unicode_ci', length=256), nullable=True))
    op.add_column('invoices', sa.Column('country_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
