"""Add currency to invoices

Revision ID: 9a9e11c72d3c
Revises: a1743bf06a76
Create Date: 2025-07-07 15:25:37.892819

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a9e11c72d3c'
down_revision = 'a1743bf06a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('currency_code', sa.String(length=3), nullable=False))
    op.execute("UPDATE invoices SET currency_code = 'USD'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'currency_code')
    # ### end Alembic commands ###
