"""generalize currencies

Revision ID: 9cdea7e8e1b2
Revises: 54b6dfefd613
Create Date: 2024-10-31 09:37:04.166953

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9cdea7e8e1b2'
down_revision = '54b6dfefd613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'shipping_usd', existing_type=mysql.NUMERIC(10, 2), new_column_name='shipping_cur1')
    op.alter_column('orders', 'shipping_rur', existing_type=mysql.NUMERIC(10, 2), new_column_name='shipping_cur2')
    op.alter_column('orders', 'subtotal_usd', existing_type=mysql.NUMERIC(10, 2), new_column_name='subtotal_cur1')
    op.alter_column('orders', 'subtotal_rur', existing_type=mysql.NUMERIC(10, 2), new_column_name='subtotal_cur2')
    op.alter_column('orders', 'total_usd', existing_type=mysql.NUMERIC(10, 2), new_column_name='total_cur1')
    op.alter_column('orders', 'total_rur', existing_type=mysql.NUMERIC(10, 2), new_column_name='total_cur2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'shipping_cur1', existing_type=mysql.NUMERIC(10, 2), new_column_name='shipping_usd')
    op.alter_column('orders', 'shipping_cur2', existing_type=mysql.NUMERIC(10, 2), new_column_name='shipping_rur')
    op.alter_column('orders', 'subtotal_cur1', existing_type=mysql.NUMERIC(10, 2), new_column_name='subtotal_usd')
    op.alter_column('orders', 'subtotal_cur2', existing_type=mysql.NUMERIC(10, 2), new_column_name='subtotal_rur')
    op.alter_column('orders', 'total_cur1', existing_type=mysql.NUMERIC(10, 2), new_column_name='total_usd')
    op.alter_column('orders', 'total_cur2', existing_type=mysql.NUMERIC(10, 2), new_column_name='total_rur')
    # ### end Alembic commands ###
