"""company default

Revision ID: 9d7da9e4aece
Revises: f5a4759da320
Create Date: 2022-01-17 20:18:25.623241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d7da9e4aece'
down_revision = 'f5a4759da320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('default', sa.Boolean(), nullable=True))
    op.execute("UPDATE companies JOIN (SELECT MIN(id) AS mid FROM companies) AS c SET `default` = 1 WHERE id = c.mid")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'default')
    # ### end Alembic commands ###
