"""empty message

Revision ID: a1743bf06a76
Revises: f822172d5329
Create Date: 2025-06-02 15:27:35.633549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1743bf06a76'
down_revision = 'f822172d5329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcustomers', sa.Column('center_code', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subcustomers', 'center_code')
    # ### end Alembic commands ###
