"""postponed orders

Revision ID: a19ef18c7c75
Revises: 7d59f47a0119
Create Date: 2020-12-06 17:55:10.149237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a19ef18c7c75'
down_revision = '7d59f47a0119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('attached_order_id', sa.String(length=16), nullable=True))
    op.create_foreign_key(None, 'orders', 'orders', ['attached_order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'attached_order_id')
    # ### end Alembic commands ###
