"""Network nodes

Revision ID: a236ef13b695
Revises: 765bc51caf4e
Create Date: 2021-02-20 18:25:04.314872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a236ef13b695'
down_revision = '765bc51caf4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('network_nodes', sa.Column('has_children', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_network_nodes_has_children'), 'network_nodes', ['has_children'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_network_nodes_has_children'), table_name='network_nodes')
    op.drop_column('network_nodes', 'has_children')
    # ### end Alembic commands ###
