"""purchase orders, vendors, address

Revision ID: a50a4a4775ca
Revises: fc6251470867
Create Date: 2020-10-08 17:55:58.615449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a50a4a4775ca'
down_revision = 'fc6251470867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('when_created', sa.DateTime(), nullable=True),
    sa.Column('when_changed', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('zip', sa.String(length=5), nullable=True),
    sa.Column('address_1', sa.String(length=64), nullable=True),
    sa.Column('address_2', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_when_created'), 'addresses', ['when_created'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('when_created', sa.DateTime(), nullable=True),
    sa.Column('when_changed', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('tax_id_1', sa.Integer(), nullable=True),
    sa.Column('tax_id_2', sa.Integer(), nullable=True),
    sa.Column('tax_id_3', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=13), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_when_created'), 'vendors', ['when_created'], unique=False)
    op.create_table('purchase_order',
    sa.Column('when_created', sa.DateTime(), nullable=True),
    sa.Column('when_changed', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=23), nullable=False),
    sa.Column('suborder_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('contact_phone', sa.String(length=13), nullable=True),
    sa.Column('payment_phone', sa.String(length=13), nullable=True),
    sa.Column('payment_account', sa.String(length=16), nullable=True),
    sa.Column('status', sa.Enum('pending', 'posted', 'paid', 'delivered', 'failed', name='purchaseorderstatus'), nullable=True),
    sa.Column('zip', sa.String(length=5), nullable=True),
    sa.Column('address_1', sa.String(length=64), nullable=True),
    sa.Column('address_2', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['subcustomers.id'], ),
    sa.ForeignKeyConstraint(['suborder_id'], ['suborders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_when_created'), 'purchase_order', ['when_created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_order_when_created'), table_name='purchase_order')
    op.drop_table('purchase_order')
    op.drop_index(op.f('ix_vendors_when_created'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_addresses_when_created'), table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
