"""order product - quantity

Revision ID: a550987b06fd
Revises: 8caad29d2ae7
Create Date: 2020-07-18 21:47:06.732711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a550987b06fd'
down_revision = '8caad29d2ae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_products', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_products', 'quantity')
    # ### end Alembic commands ###
