"""add user to order

Revision ID: a5da79b33042
Revises: 2f443ba08e05
Create Date: 2020-07-25 20:17:39.262030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5da79b33042'
down_revision = '2f443ba08e05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_user_id', table_name='orders')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_index('ix_orders_user_id', 'orders', ['user_id'], unique=False)
    # ### end Alembic commands ###
