"""shipping

Revision ID: ae8c4350a838
Revises: cbfc98ab4350
Create Date: 2020-07-16 16:09:59.210518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae8c4350a838'
down_revision = 'cbfc98ab4350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination', sa.String(length=32), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipping_rates_destination'), 'shipping_rates', ['destination'], unique=False)
    op.create_index(op.f('ix_shipping_rates_weight'), 'shipping_rates', ['weight'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipping_rates_weight'), table_name='shipping_rates')
    op.drop_index(op.f('ix_shipping_rates_destination'), table_name='shipping_rates')
    op.drop_table('shipping_rates')
    # ### end Alembic commands ###
