"""product exempt from purchase

Revision ID: b041a9757d61
Revises: 2e5885e58757
Create Date: 2020-10-27 21:38:04.161891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b041a9757d61'
down_revision = '2e5885e58757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('purchase', sa.Boolean(), nullable=True))
    op.execute('UPDATE products SET purchase=1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'purchase')
    # ### end Alembic commands ###
