"""order buyout date

Revision ID: b403db478ec4
Revises: 827efe43c06c
Create Date: 2020-09-17 20:00:51.844730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b403db478ec4'
down_revision = '827efe43c06c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('buyout_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_orders_buyout_date'), 'orders', ['buyout_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_buyout_date'), table_name='orders')
    op.drop_column('orders', 'buyout_date')
    # ### end Alembic commands ###
