"""invoice customer name

Revision ID: b6ccd90b4c43
Revises: 32141851936f
Create Date: 2020-09-30 17:45:08.524175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b6ccd90b4c43'
down_revision = '32141851936f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('name', sa.String(length=128), nullable=True))
    op.alter_column('orders', 'status',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=16),
               type_=sa.Enum('pending', 'paid', 'shipped', 'complete', name='orderstatus'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('pending', 'paid', 'shipped', 'complete', name='orderstatus'),
               type_=mysql.VARCHAR(collation='utf8_unicode_ci', length=16),
               existing_nullable=True)
    op.drop_column('invoices', 'name')
    # ### end Alembic commands ###
