"""flask-security-too

Revision ID: bb04eb95150a
Revises: 543be56f2401
Create Date: 2021-11-24 07:21:39.485338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb04eb95150a'
down_revision = '543be56f2401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pv_stats_permissions', 'node_id',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=8),
               nullable=True)
    op.add_column('users', sa.Column('fs_uniquifier', sa.String(length=255), nullable=False))
    op.execute("UPDATE users SET fs_uniquifier = id")
    op.create_unique_constraint(None, 'users', ['fs_uniquifier'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'fs_uniquifier')
    # ### end Alembic commands ###
