"""

Revision ID: bda39dafb2ed
Revises: 75e1827e3062
Create Date: 2020-10-09 22:10:26.741476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bda39dafb2ed'
down_revision = '75e1827e3062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_methods', sa.Column('payee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payment_methods', 'companies', ['payee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_methods', type_='foreignkey')
    op.drop_column('payment_methods', 'payee_id')
    # ### end Alembic commands ###
