"""enable/disable payment method

Revision ID: be17c0af1d19
Revises: 3bfc6b263f5a
Create Date: 2022-11-11 12:40:14.595554

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be17c0af1d19'
down_revision = '3bfc6b263f5a'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('payment_methods', sa.Column('enabled', sa.Boolean(), nullable=True))
    op.execute('UPDATE payment_methods SET enabled=1')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_methods', 'enabled')
    # ### end Alembic commands ###
