"""Shipping method enablement

Revision ID: c01aefec05ef
Revises: 5a9f34337673
Create Date: 2021-02-11 15:14:25.029068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c01aefec05ef'
down_revision = '5a9f34337673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipping', sa.Column('enabled', sa.Boolean(), server_default='1', nullable=True))
    op.execute("UPDATE shipping SET enabled=1")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipping', 'enabled')
    # ### end Alembic commands ###
