"""invoice

Revision ID: c3476be93596
Revises: fb63156e6662
Create Date: 2020-07-31 05:46:41.676015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3476be93596'
down_revision = 'fb63156e6662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('when_created', sa.DateTime(), nullable=True),
    sa.Column('when_changed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('invoice_id', sa.String(length=16), nullable=True))
    op.create_foreign_key(None, 'orders', 'invoices', ['invoice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'invoice_id')
    op.drop_table('invoices')
    # ### end Alembic commands ###
