"""sale order purchase date

Revision ID: c3c22990455c
Revises: 2a593c9fcb67
Create Date: 2020-11-29 17:58:32.301944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3c22990455c'
down_revision = '2a593c9fcb67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('purchase_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'purchase_date')
    # ### end Alembic commands ###
