"""invoice payee

Revision ID: cb02ec280203
Revises: 9819add7f80f
Create Date: 2021-01-24 15:16:34.160509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb02ec280203'
down_revision = '9819add7f80f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('payee', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'payee')
    # ### end Alembic commands ###
