"""product color

Revision ID: ce6116c4088b
Revises: 7b5e946d0a00
Create Date: 2021-03-12 09:14:06.056074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce6116c4088b'
down_revision = '7b5e946d0a00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('color', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'color')
    # ### end Alembic commands ###
