"""order status and tracking

Revision ID: d15275bc51d4
Revises: 01e8a99d4b1e
Create Date: 2020-09-01 18:14:47.013022

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd15275bc51d4'
down_revision = '01e8a99d4b1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.String(length=16), nullable=True))
    op.add_column('orders', sa.Column('tracking_id', sa.String(length=64), nullable=True))
    op.add_column('orders', sa.Column('tracking_url', sa.String(length=256), nullable=True))
    op.add_column('orders', sa.Column('when_changed', sa.DateTime(), nullable=True))
    op.alter_column('orders', 'address',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=128),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('orders', 'phone',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=32),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('users', 'enabled',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'enabled',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('orders', 'phone',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(collation='utf8_unicode_ci', length=32),
               existing_nullable=True)
    op.alter_column('orders', 'address',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(collation='utf8_unicode_ci', length=128),
               existing_nullable=True)
    op.drop_column('orders', 'when_changed')
    op.drop_column('orders', 'tracking_url')
    op.drop_column('orders', 'tracking_id')
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
