"""order product status rework

Revision ID: d34ae5586298
Revises: a19ef18c7c75
Create Date: 2020-12-08 21:41:57.523418

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd34ae5586298'
down_revision = 'a19ef18c7c75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_product_status_history', 'set_at',
               new_column_name='when_created',
               existing_type=sa.DateTime(),
               existing_nullable=False)
    op.execute('UPDATE order_products SET status=\'pending\' WHERE status=\'Waiting\'')
    op.execute('UPDATE order_products SET status=\'pending\' WHERE status IS NULL')
    op.execute('UPDATE order_products SET status=\'po_created\' WHERE status=\'ordered\'')
    op.execute('UPDATE order_products SET status=\'purchased\' WHERE status=\'Purchased\'')
    op.execute('UPDATE order_products SET status=\'shipped\' WHERE status=\'Shipped\'')
    op.execute('UPDATE order_products SET status=\'complete\' WHERE status=\'Complete\'')
    op.execute('UPDATE order_product_status_history SET status=\'pending\' WHERE status=\'Waiting\'')
    op.execute('UPDATE order_product_status_history SET status=\'pending\' WHERE status IS NULL')
    op.execute('UPDATE order_product_status_history SET status=\'po_created\' WHERE status=\'ordered\'')
    op.execute('UPDATE order_product_status_history SET status=\'purchased\' WHERE status=\'Purchased\'')
    op.execute('UPDATE order_product_status_history SET status=\'shipped\' WHERE status=\'Shipped\'')
    op.execute('UPDATE order_product_status_history SET status=\'complete\' WHERE status=\'Complete\'')
    op.alter_column('order_product_status_history', 'status',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=16),
               type_=sa.Enum('pending', 'po_created', 'unavailable', 'purchased', 'shipped', 'complete', 'cancelled', name='orderproductstatus'),
               existing_nullable=True)
    op.alter_column('order_products', 'status',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=16),
               type_=sa.Enum('pending', 'po_created', 'unavailable', 'purchased', 'shipped', 'complete', 'cancelled', name='orderproductstatus'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_product_status_history', 'when_created',
               new_column_name='set_at',
               existing_type=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('order_products', 'status',
               existing_type=sa.Enum('pending', 'po_created', 'unavailable', 'purchased', 'shipped', 'complete', 'cancelled', name='orderproductstatus'),
               type_=mysql.VARCHAR(collation='utf8_unicode_ci', length=16),
               existing_nullable=True)
    op.alter_column('order_product_status_history', 'status',
               existing_type=sa.Enum('pending', 'po_created', 'unavailable', 'purchased', 'shipped', 'complete', 'cancelled', name='orderproductstatus'),
               type_=mysql.VARCHAR(collation='utf8_unicode_ci', length=16),
               existing_nullable=True)
    # ### end Alembic commands ###
