"""address

Revision ID: d41fcb00aa71
Revises: 8a808621504d
Create Date: 2021-07-11 11:53:11.069486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd41fcb00aa71'
down_revision = '8a808621504d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('country_id', sa.String(length=2), nullable=True))
    op.add_column('addresses', sa.Column('user_created', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'addresses', 'countries', ['country_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.drop_column('addresses', 'user_created')
    op.drop_column('addresses', 'country_id')
    # ### end Alembic commands ###
