"""order customer name

Revision ID: d486c27d07cf
Revises: 108624ed5665
Create Date: 2020-12-20 20:00:41.157492

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd486c27d07cf'
down_revision = '108624ed5665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'name', new_column_name='customer_name', existing_type=mysql.VARCHAR(64))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'customer_name', new_column_name='name', existing_type=mysql.VARCHAR(64))
    # ### end Alembic commands ###
