"""pv stats

Revision ID: db95ef2597b7
Revises: b264cc731cf1
Create Date: 2021-11-18 12:05:55.523049

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db95ef2597b7'
down_revision = 'b264cc731cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pv_stats_permissions',
    sa.Column('when_created', sa.DateTime(), nullable=True),
    sa.Column('when_changed', sa.DateTime(), nullable=True),
    sa.Column('node_id', sa.String(length=8), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('node_id', 'user_id')
    )
    op.create_index(op.f('ix_pv_stats_permissions_when_created'), 'pv_stats_permissions', ['when_created'], unique=False)
    op.drop_column('order_products_warehouses', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_products_warehouses', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_pv_stats_permissions_when_created'), table_name='pv_stats_permissions')
    op.drop_table('pv_stats_permissions')
    # ### end Alembic commands ###
