"""product availability

Revision ID: deaf42a8c083
Revises: 26142232272e
Create Date: 2020-08-09 20:46:08.371375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deaf42a8c083'
down_revision = '26142232272e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'available')
    # ### end Alembic commands ###
