"""purchase order table rename

Revision ID: e33cd5017043
Revises: 9fd17d9dcd45
Create Date: 2020-10-11 19:41:06.703820

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e33cd5017043'
down_revision = '9fd17d9dcd45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_orders',
    sa.Column('when_created', sa.DateTime(), nullable=True),
    sa.Column('when_changed', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=23), nullable=False),
    sa.Column('suborder_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('contact_phone', sa.String(length=13), nullable=True),
    sa.Column('payment_phone', sa.String(length=13), nullable=True),
    sa.Column('payment_account', sa.String(length=16), nullable=True),
    sa.Column('status', sa.Enum('pending', 'paid', 'delivered', name='purchaseorderstatus'), nullable=True),
    sa.Column('zip', sa.String(length=5), nullable=True),
    sa.Column('address_1', sa.String(length=64), nullable=True),
    sa.Column('address_2', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['subcustomers.id'], ),
    sa.ForeignKeyConstraint(['suborder_id'], ['suborders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_when_created'), 'purchase_orders', ['when_created'], unique=False)
    op.drop_index('ix_purchase_order_when_created', table_name='purchase_order')
    op.drop_table('purchase_order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_order',
    sa.Column('when_created', mysql.DATETIME(), nullable=True),
    sa.Column('when_changed', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.VARCHAR(collation='utf8_unicode_ci', length=23), nullable=False),
    sa.Column('suborder_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('contact_phone', mysql.VARCHAR(collation='utf8_unicode_ci', length=13), nullable=True),
    sa.Column('payment_phone', mysql.VARCHAR(collation='utf8_unicode_ci', length=13), nullable=True),
    sa.Column('payment_account', mysql.VARCHAR(collation='utf8_unicode_ci', length=16), nullable=True),
    sa.Column('status', mysql.ENUM('pending', 'paid', 'delivered', collation='utf8_unicode_ci'), nullable=True),
    sa.Column('zip', mysql.VARCHAR(collation='utf8_unicode_ci', length=5), nullable=True),
    sa.Column('address_1', mysql.VARCHAR(collation='utf8_unicode_ci', length=64), nullable=True),
    sa.Column('address_2', mysql.VARCHAR(collation='utf8_unicode_ci', length=64), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['subcustomers.id'], name='purchase_order_ibfk_1'),
    sa.ForeignKeyConstraint(['suborder_id'], ['suborders.id'], name='purchase_order_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_purchase_order_when_created', 'purchase_order', ['when_created'], unique=False)
    op.drop_index(op.f('ix_purchase_orders_when_created'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    # ### end Alembic commands ###
