"""currency format

Revision ID: e55ffafd151c
Revises: 681e38804a30
Create Date: 2021-04-02 09:27:56.409501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e55ffafd151c'
down_revision = '681e38804a30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currencies', sa.Column('decimal_places', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currencies', 'decimal_places')
    # ### end Alembic commands ###
