"""node name

Revision ID: e7708754c392
Revises: 5f479faf462c
Create Date: 2021-03-02 15:08:38.354546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e7708754c392'
down_revision = '5f479faf462c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('network_nodes', 'name',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=32),
               type_=sa.String(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('network_nodes', 'name',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(collation='utf8_unicode_ci', length=32),
               existing_nullable=True)
    # ### end Alembic commands ###
