"""products table

Revision ID: e8782d713095
Revises: 
Create Date: 2020-07-16 10:19:20.278522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8782d713095'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_english', sa.String(length=256), nullable=True),
    sa.Column('name_russian', sa.String(length=256), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_name_english'), 'products', ['name_english'], unique=False)
    op.create_index(op.f('ix_products_name_russian'), 'products', ['name_russian'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_name_russian'), table_name='products')
    op.drop_index(op.f('ix_products_name_english'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
