"""order drafts

Revision ID: ec91441f2b81
Revises: 2d60fd0fb3cd
Create Date: 2021-04-22 19:26:02.952116

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec91441f2b81'
down_revision = '2d60fd0fb3cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_products_ibfk_3', 'order_products', type_='foreignkey')
    op.create_foreign_key(None, 'order_products', 'suborders', ['suborder_id'], ['id'], onupdate='CASCADE')
    op.drop_constraint('suborders_ibfk_1', 'suborders', type_='foreignkey')
    op.create_foreign_key(None, 'suborders', 'orders', ['order_id'], ['id'], onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    pass
