"""notifications

Revision ID: ee4fffe608b7
Revises: 8c9957eafdb4
Create Date: 2021-04-13 14:40:10.837572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee4fffe608b7'
down_revision = '8c9957eafdb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('when_created', sa.DateTime(), nullable=True),
    sa.Column('when_changed', sa.DateTime(), nullable=True),
    sa.Column('short_desc', sa.String(length=128), nullable=True),
    sa.Column('long_desc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_when_created'), 'notification', ['when_created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_when_created'), table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###
