"""product color

Revision ID: f22c2a205ef2
Revises: ce6116c4088b
Create Date: 2021-03-13 19:49:54.085495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f22c2a205ef2'
down_revision = 'ce6116c4088b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'color',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=7),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'color',
               existing_type=sa.String(length=7),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
