"""user profile

Revision ID: f3e2e50e0c92
Revises: e55ffafd151c
Create Date: 2021-04-03 21:04:36.531184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3e2e50e0c92'
down_revision = 'e55ffafd151c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile', sa.Text(), nullable=True))
    op.execute('UPDATE users SET profile = \'{}\'')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile')
    # ### end Alembic commands ###
