"""add posting status to PurchaseOrderStatus

Revision ID: fa01a9d1354f
Revises: a1b2c3d4e5f6
Create Date: 2026-04-13 18:30:50.906145

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa01a9d1354f'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE purchase_orders MODIFY status "
        "ENUM('pending','partially_posted','posted','paid','payment_past_due',"
        "'shipped','delivered','failed','cancelled','posting')"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE purchase_orders MODIFY status "
        "ENUM('pending','partially_posted','posted','paid','payment_past_due',"
        "'shipped','delivered','failed','cancelled')"
    )

    # ### end Alembic commands ###
