"""phone length 32

Revision ID: fa6736e5137e
Revises: 56cb08719d24
Create Date: 2021-03-27 17:19:24.887666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa6736e5137e'
down_revision = '56cb08719d24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=16),
               type_=sa.String(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=16),
               existing_nullable=True)
    # ### end Alembic commands ###
