"""user model update

Revision ID: fb63156e6662
Revises: e3ab0fd6e7a1
Create Date: 2020-07-30 11:51:50.250882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb63156e6662'
down_revision = 'e3ab0fd6e7a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'enabled')
    # ### end Alembic commands ###
