"""product separate shipping

Revision ID: fc5d56eb3657
Revises: 166a85d1f865
Create Date: 2020-10-02 13:08:27.468882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc5d56eb3657'
down_revision = '166a85d1f865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('separate_shipping', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'separate_shipping')
    # ### end Alembic commands ###
