"""product separate shipping

Revision ID: fc6251470867
Revises: fc5d56eb3657
Create Date: 2020-10-03 18:00:29.466369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc6251470867'
down_revision = 'fc5d56eb3657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suborders', sa.Column('local_shipping', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suborders', 'local_shipping')
    # ### end Alembic commands ###
